spring:
  cloud:
    stream:
      function:
        definition: cardSupplier;cardEventConsumer
      bindings:
          cardSupplier-out-0:
              destination: card-events
          cardEventConsumer-in-0:
              destination: card-events
              group: card-consumer
