spring:
  cloud:
    stream:
      default:
        producer:
          useNativeEncoding: true
        consumer:
          useNativeEncoding: true
      default-binder: kafka
      function:
        definition: cardSupplier;cardEventConsumer;upperCase
      bindings:
          cardSupplier-out-0:
              destination: card-events
              content-type: application/*+avro
          cardEventConsumer-in-0:
              destination: card-events
              content-type: application/*+avro
              group: card-consumer
      kafka:
            binder:
              producer-properties:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                schema.registry.url: http://localhost:8081
              consumer-properties:
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                schema.registry.url: http://localhost:8081
                specific.avro.reader: true
